services:
  php-app:
    build: 
      context: .
      dockerfile: docker_images/php/DockerFile.yml
    tty: true
    container_name: PHP
    ports:
      - 3333:8000
    networks:
      - external-network
    command: bash -c "cd /app && composer start"

networks:
  external-network:
