services:
  - name: php-app
    type: web
    env: docker
    repo: https://github.com/migdev23/daw2_clmskills_2018_rodriguez_miguel
    plan: free
    region: oregon
    branch: main
    dockerContext: .
    dockerfilePath: docker_images/php/DockerFile.yml
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mariadb-instance
          property: connectionString
    ports:
      - 3333

  - name: mariadb-instance
    type: mariadb
    plan: free
    region: oregon
    databaseName: mydb
    user: root
    envVars:
      - key: MARIADB_ROOT_PASSWORD
        value: 2025_skills
