FROM php:8.2.27

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip && docker-php-ext-install pdo pdo_mysql


COPY --from=composer:2.8.4 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . /app

RUN composer i
